### ISSUE TITLE
Top parameter names oddly named in docs

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMX-Software/pflib#11]
**Describe the bug**
Some of the parameters in the Top page are named very weirdly. It seems like[ the documentation](https://github.com/tomeichlersmith/ldmx-cob/blob/main/notes/ASIC_parameters_HGCROC_for_SiPM.pdf) for that sub-block differs in structure from the docs for the other sub-blocks.

**Expected behavior**
These registers are split into three actual parameter values.
amplitude, pre-emphasis, pre-emphasis phase

reg 4 - probe pll
reg 5 - actual readout data
div_pll

N, S0, S1 are floating around for some reason?

@jmmans Please update with details if I said anything wrong.

**Comment by jmmans** [comment]
Perhaps this is clearer?
"DIV_PLL_A" -> DIV_PLL<0>
"DIV_PLL_B" -> DIV_PLL<1>
"ENx_probe_pll" -> PLL_probe_amplitude (three bit field)
"EN-pEx_probe_pll" -> PLL_probe_pre_scale (three bit field)
"S0_probe_pll" -> PLL_probe_pre_phase (two bit field)
"EN1/2/3" -> eTx_amplitude (three bit field)
"EN-p0/1/2" -> eTx_pre_scale (three bit field)
"S0/1" -> eTx_pre_phase (two bit field)
