### ISSUE TITLE
DMA Readout

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMX-Software/pflib#20]
@pbutti @slacrherbst Can you copy the instructions here?

**Comment by pbutti** [comment]
Hi!
I do not have DMA readout standalone sw. If the instructions were provided in the past, perhaps @slacrherbst  @bengineerd have some info.
If you need I can point you to the line where rogue reads from AxiStreamDma, but I'm sure you have already seen that?

**Comment by tomeichlersmith** [comment]
For potentially future reference:
```python
self.febSrpTdests = [i*16 for i in range(12)]
self.febSrpDmaChannels = [rogue.hardware.axi.AxiStreamDma('/dev/axi_stream_dma_0', dest, True) for dest in self.febSrpTdests]
```

**Comment by tomeichlersmith** [comment]
Helpful resources from Ryan:
https://github.com/slaclab/aes-stream-drivers/blob/main/rce_stream/app/src/dmaRead.cpp
