### ISSUE TITLE
Add a less disruptive relink procedure

### ISSUE THREAD

**Issue by cmantill** [LDMX-Software/pflib#41]
The current `RELINK` functionality does a hard reset to the PLL, sets the delays and does a scan of bitslips for ALL elinks. This is a bit disruptive if some elinks were already showing good idles.

We would like a functionality where the PLL is not reset and we just re-scan bitslip for one single elink.

**Comment by tomeichlersmith** [comment]
This is now on main

https://github.com/LDMX-Software/pflib/blob/d53be0051921f7951f034d2abc5bf1aa8c07ff80/src/pflib/PolarfireTarget.cxx#L465-L521

so I'm closing this issue
