### ISSUE TITLE
Implement a task menu

### ISSUE THREAD

**Issue by cmantill** [LDMX-Software/pflib#42]
It would be nice to include a task menu in pftool.

Some tasks that we have talked about:
- Initial configuration after power up (e.g. after power-cycling the chip, re-loading the firmware). Would probably want something along: `FC.RESET`, `ROC.RESYNCLOAD`, `ELINKS.RESET`, `DAQ.RESET`.
- A phase scan
- A calib scan 
These two are mentioned in [iss_40](https://github.com/LDMX-Software/pflib/issues/40).

More can be added.

**Comment by tomeichlersmith** [comment]
Begun with #69
