### ISSUE TITLE
Tool to tune TOT

### ISSUE THREAD

**Issue by Skelpdar** [LDMX-Software/pflib#49]
Charge injections can be used to find at which ADC tick the TOT fires. 

We could make a tool in the TASK menu to allow tuning tot_vref, so the TOT fires at an ADC value of our choosing.

**Comment by tomeichlersmith** [comment]
**just notes**

1. set `tot_vref` to maximum to allow ADC to find peak given a `calib_dac` value
2. choose ADC value and move calib_dac to find at which value the ADC attains that peak
3. Lower `tot_vref` until TOT triggers at that `calib_dac`

**Comment by tomeichlersmith** [comment]
We have several tools now merged into main that allow the user to tune the TOT. This issue can be re-opened if I am incorrect or if a new issue is not pertinent.
