### ISSUE TITLE
Add options for interfacing with bias for only for boards with active links

### ISSUE THREAD

**Issue by EinarElen** [LDMX-Software/pflib#79]
Currently, we are unable to communicate with the bias of one of the boards. This means that the functions that interact with all of the boards at once aren't useable, which means you have to do things manually which is slower. You could get around this by only interfacing with the bias of boards that have at least one ELINK enabled. I'm not sure if you would want this to replace the currrent behaviour or if it is useful to have both options.

**Comment by tomeichlersmith** [comment]
Resolved by PR #80
